name: 🐛 Bug Report
description: Create a report to help us improve Orquestra
title: "[BUG] <Short description of the bug>"
labels: ["bug", "needs-triage"]
assignees:
  - # Add GitHub usernames of maintainers here if desired, e.g., orquestra-ai-bot
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! 
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: "e.g., The application crashes when selecting the 'Grover (2-qubit)' circuit after enabling fault tolerance."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "e.g., The resource estimation should complete and display results for the Grover circuit."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: "e.g., An error message 'Calculation failed: undefined property' appeared, and no results were shown."
    validations:
      required: true

  - type: input
    id: orquestra-version
    attributes:
      label: Orquestra Version
      description: "Which version of Orquestra are you using? (e.g., v0.1.0, or commit hash if building from source)"
      placeholder: "e.g., v0.1.0 or main branch commit abc1234"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Specify distribution in 'Additional Context' if relevant)
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser (if UI bug)
      description: "If this is a UI bug, which browser and version are you using? (e.g., Chrome 120.0.0.0, Firefox 119.0)"
      placeholder: "e.g., Chrome 120.0.0.0"
    validations:
      required: false

  - type: input
    id: python-version
    attributes:
      label: Python Version (if SDK bug)
      description: "If this bug relates to the Python SDK, which Python version are you using? (e.g., 3.10.9)"
      placeholder: "e.g., 3.10.9"
    validations:
      required: false
      
  - type: input
    id: node-version
    attributes:
      label: Node.js Version (if UI/Build bug)
      description: "If this bug relates to the UI build or development server, which Node.js version are you using? (e.g., v18.17.0)"
      placeholder: "e.g., v18.17.0"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        - Screenshots or error messages (please use code blocks for logs/errors).
        - Specific hardware architecture models used, if relevant.
        - Any unusual setup or environment details.
      placeholder: "Provide logs, screenshots, or any other relevant information."
      render: markdown
    validations:
      required: false
